export default function layout() {
  return (
    <div>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <h1>hello!</h1>
      <p>yoooo</p>
      <p>yoooo</p>
      <p>yoooo</p>
      <p>yoooo</p>
      <p>yoooo</p>
    </div>
  );
}
